# Generated by Django 6.0.5 on 2026-06-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.URLField(blank=True, null=True),
        ),
    ]
